---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  annotations:
    ingressClassName: nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - nexus.cg5labs.net
      secretName: nexus-tls
  rules:
  - host: "nexus.cg5labs.net"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nexus
              port: 
                number: 8081
  - host: "nexus.cg5labs.ddns.net"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: nexus
              port: 
                number: 8081

