apiVersion: v1
kind: Service
metadata:
  name: app01-svc
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 5678
  selector:
    app: app01
  type: NodePort
status:
  loadBalancer: {}
