---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-example2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://cg5labs.github.io/helm-charts/'
    targetRevision: 0.1.0
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: replicaCount
          value: "3"
    chart: helm-example2
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cleanroom 
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
