apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jspwiki
  name: jspwiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jspwiki
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jspwiki
    spec:
      containers:
      - name:  jspwiki
        image: apache/jspwiki
        volumeMounts:
        - name: jspwiki-nfs
          mountPath: /var/jspwiki/pages
        #args: 
        #- "/usr/local/tomcat/bin/catalina.sh"
        #- "run"
        ports:
        - containerPort: 8080
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: jspwiki-nfs
          persistentVolumeClaim:
            claimName: jspwiki
