apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jspwiki
  name: jspwiki
spec:
  containers:
  - name: jspwiki
    image: apache/jspwiki
    ports:
    - containerPort: 8080
    #args: 
    #- "/usr/local/tomcat/bin/catalina.sh"
    #- "run"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
