---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runners
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cg5labs/k8s-examples.git'
    path: gha-runners
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: actions-runner-system
  syncPolicy:
    automated:
      selfHeal: true
