---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://emberstack.github.io/helm-charts'
    targetRevision: "7.0.151"
    helm:
    chart: reflector
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: infra
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
