---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://cg5labs.github.io/helm-charts/'
    targetRevision: "1.11.1"
    helm:
      parameters:
      - name: "installCRDs"
        value: "true"
      valueFiles:
        - values.yaml
    chart: cert-manager-subchart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
