apiVersion: v1
kind: Service
metadata:
  name: banana
  annotations:
    metallb.universe.tf/address-pool: default
    kubernetes.io/change-cause: "CRQ-221: LB switch to green"
spec:
  selector:
    run: banana-green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  type: LoadBalancer
