apiVersion: v1
kind: Service
metadata:
  name: banana-test
  annotations:
    metallb.universe.tf/address-pool: default
    kubernetes.io/change-cause: "CRQ-001: Switch to blue"
spec:
  selector:
    run: banana-blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5678
  type: LoadBalancer
