---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/cg5labs/k8s-examples.git'
    path: nginx
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cleanroom
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
