---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: default
  source:
    repoURL: https://github.com/cg5labs/k8s-examples/
    path: efk/fluentd
    targetRevision: HEAD
    directory:
      recurse: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

