apiVersion: v1
data:
  default.conf: |+
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /upload {
          root   /usr/share/nginx;
          client_max_body_size 10000m;
          dav_methods  PUT DELETE MKCOL COPY MOVE;
          create_full_put_path   on;
          dav_access             group:rw  all:r;
        }

    }
kind: ConfigMap
metadata:
  name: nginx-cm
