---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        fluentd: "true"
    spec:
      nodeName: xsrv007
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
        env:
          - name: NGINX_ENV_SETTING
            valueFrom:
              configMapKeyRef:
                name: nginx-cm
                key: custom_variable
          - name: NGINX_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: password
        volumeMounts:
        - name: nfs-test
          mountPath: /usr/share/nginx/html
        - name: config-vol
          mountPath: /etc/nginx/conf.d
        - name: upload-vol
          mountPath: /usr/share/nginx/upload
      volumes:
        - name: nfs-test
          persistentVolumeClaim:
            claimName: sc-nfs-pvc
        - name: upload-vol
          emptyDir: {}
        - name: config-vol
          configMap:
            name: nginx-cm
            items:
            - key: default.conf
              path: default.conf

