apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        fluentd: "true"
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-vol
          mountPath: /etc/nginx/conf.d
        - name: upload-vol
          mountPath: /usr/share/nginx/upload
      volumes:
        - name: upload-vol
          emptyDir: {}
        - name: config-vol
          configMap:
            name: nginx-cm
            items:
            - key: default.conf
              path: default.conf

