apiVersion: v1
data:
  payload.json: |+
    {
      "index_patterns": ["logstash-*"],
      "template": {
        "settings": {
          "index": {
            "lifecycle": {
              "name": "hot-warm-delete",
              "rollover_alias": "logstash"
            },
            "routing": {
              "allocation": {
                "include": {
                  "_tier_preference": "data_content"
                }
              }
            },
            "number_of_shards": "1",
            "number_of_replicas": "0"
          }
        },
        "aliases": {
          "logstash": {}
        },
        "mappings": {}
      }
    }

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: es-customizer
