apiVersion: v1
data:
  it_logstash.json: |+
    {
      "index_patterns": ["logstash-*"],
      "template": {
        "settings": {
          "index": {
            "lifecycle": {
              "name": "hot-warm-delete",
              "rollover_alias": "logstash"
            },
            "routing": {
              "allocation": {
                "include": {
                  "_tier_preference": "data_content"
                }
              }
            },
            "number_of_shards": "1",
            "number_of_replicas": "0"
          }
        },
        "aliases": {
          "logstash": {}
        },
        "mappings": {}
      }
    }
  ilp_hot-warm-delete.json: |+
    {
      "policy": {
        "phases": {
          "hot": {
            "min_age": "0ms",
            "actions": {
              "set_priority": {
                "priority": 100
              }
            }
          },
          "warm": {
            "min_age": "5d",
            "actions": {
              "set_priority": {
                "priority": 50
              }
            }
          },
          "delete": {
            "min_age": "10d",
            "actions": {
              "delete": {
                "delete_searchable_snapshot": true
              }
            }
          }
        }
      }
    }

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: es-customizer
