apiVersion: batch/v1
kind: Job
metadata:
  name: escustomizer
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: curl
        image: quay.io/curl/curl:latest
        args:
        - "/bin/sh"
        - "-c"
        - "eval ${ES_CURL_CMD}"
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        env:
        - name: ES_DEBUG # set to '-v' for debug
          value: ""
        - name: ES_URL_BASE
          value: "https://elk-es-http.monitoring.svc:9200"
        - name: ES_URL_TEMPLATE
          value: "_index_template/logstash"
        - name: ES_URL_HEADER
          value: "Content-Type: application/json"
        - name: ES_CURL_CMD
          value: "curl -k ${ES_DEBUG} -u elastic:${ES_API_AUTH} -H \"${ES_URL_HEADER}\" -X PUT -d @/config/payload.json ${ES_URL_BASE}/${ES_URL_TEMPLATE}"
        - name: ES_API_AUTH
          valueFrom:
            secretKeyRef:
              name: elk-es-elastic-user
              key: elastic
      volumes:
      - name: config
        configMap:
          name: es-deployer
