---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx/'
    targetRevision: 4.6.0
    helm:
      parameters:
        - name: controller.kind
          value: DaemonSet
        - name: controller.service.type
          value: NodePort
        - name: controller.service.externalTrafficPolicy
          value: Local
        #- name: controller.extraArgs.default-ssl-certificate
          #value: nexus/nexus-tls
    chart: ingress-nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true

