---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: 'https://cg5labs.github.io/helm-charts/'
    targetRevision: 45.25.3
    helm:
      skipCrds: true
      valueFiles:
        - values.yaml
    chart: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

