---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-instance
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  source:
    repoURL: 'https://github.com/cg5labs/k8s-examples.git'
    path: efk/elasticsearch/elk-instance
    targetRevision: HEAD
    directory:
      recurse: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
