---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: elastic-system
  project: default
  source:
    repoURL: 'https://helm.elastic.co'
    targetRevision: 2.4.0
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: webhook.caBundle
          value: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXVENDQWtHZ0F3SUJBZ0lRUzNSSUthc1UyVU5XU2JNOU1IK2p3akFOQmdrcWhraUc5dzBCQVFzRkFEQTMKTVJnd0ZnWURWUVFMRXc5bGJHRnpkR2xqTFhkbFltaHZiMnN4R3pBWkJnTlZCQU1URW1Wc1lYTjBhV010ZDJWaQphRzl2YXkxallUQWVGdzB5TWpFeU1UQXhOVEkyTXpoYUZ3MHlNekV5TVRBeE5UTTJNemhhTURjeEdEQVdCZ05WCkJBc1REMlZzWVhOMGFXTXRkMlZpYUc5dmF6RWJNQmtHQTFVRUF4TVNaV3hoYzNScFl5MTNaV0pvYjI5ckxXTmgKTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3MFljZGcrUDZnczFKNXF2UU16SgoydEwyVWErQ0swVDNpdlNVRGI1Y3QvcWZEeHBWODR3c0MvbUxkbmlQY1hENW5MOVBrbytDVUxQY3N5bHFjYzNNCk1lL2puVjl4ejdkTXMwbTk3aG9GZWNCVE1wM0JRcWlTQmZuM24yTGsxdTNXVXkrdTFyWURKNk9HZjdIa3FnYUsKZ0Y1U1NsQ016eitpRWI4NzlvaFZnZjlIRldIUHl0eDdRZ3FXK250YUJYVy9XVlNJKzNkbkJDbXZEOEU4cTFvMwpmYkZMQm9hbCtWMHgvS2lsdGtVSTNRWVlDQWlGSUtyRURMOWU0cGdNQ2ttL3FyR1R5a2MyS0lLWHNoa29JMkM0Ck1LN3VETzc3Ti9nL3RmM3FzWVB3V0w1ZFVFR2NJR0JYR2NxQUxMV3lSSkhUWUtOSGRINklJam1TK3FYQmZId2MKUlFJREFRQUJvMkV3WHpBT0JnTlZIUThCQWY4RUJBTUNBb1F3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFRwpDQ3NHQVFVRkJ3TUNNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGUEp5MGdWVFdUMldGTWJ3CjJiMGRQOXdYdWVQTE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkRrOWhFOTdFN29GaEJNLzI3cTk3d0YrNHMKOEFYaVFlVmd2Q1lVcDFNY3gxaU1PZEFzUjl3ZDdnWWdlWTlML004VnpkOTQ5TExiZ3VXTVhrZ3IwM0pCeGFibQoyWEpnQXVUOGF2TVhrOGY0UFBlZXY2RVhPbEZrdTJCYTJpUEg5LzBuTjlEOWgzME9uRkZ6a3JCc01sS2tKYmhtCldIZjJjd2pCU2dDbGxlVktFOTJmVFEyU2xXMkUzNnNibG10bTlWNjJUYjNJbWhrRlVoYkxmcTlhYjVDVklkYSsKYXFkODJrdmFOMi93alB1VmRpbkpDUkhmbDV4V2FQTVQ3QzhPeUtILzJFdERzTjdWdEV4RzFteVBPUmRDdVNCMwpUcTRwY1RqK2ZyRjNCZmNNWUJteWJ5bVFzdGtvWFQ0NXlDZ1RXZDRQNUNrL01SUFRHeFhwOThXQTdsZkgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    chart: eck-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elastic-system
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true

