imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: 
    ingressClassName: nginx
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.17.0/24
  hosts:
    - host: grafana.cg5labs.net
      paths:
        - path: /
          pathType: Prefix
          serviceName: kube-prometheus-subchart-grafana
          servicePort: 80
  tls: 
    - secretName: grafana-tls
      hosts:
        - grafana.cg5labs.net

